version: '3.4'
services:
  truffle:
    build:
      context: .
    image: marketprotocol/marketprotocol:2.0.1-alpha
    command: truffle develop
    tty: true
    stdin_open: true

  truffle-coverage:
    #    uses built and tagged image above
    image: marketprotocol/marketprotocol:2.0.1-alpha
    command: scripts/coverage_setup.sh