version: '3'
services:
    postgres:
        image: postgres:9.6
        environment:
            - POSTGRES_USER=api
            - POSTGRES_PASSWORD=api
            - POSTGRES_DB=api
        # persist the postgres data to disk so we don't lose it
        # on rebuilds.
        volumes:
            - ../.docker-volumes/postgres:/var/lib/postgresql/data
        ports:
            - "5432:5432"
    mesh:
        image: docker.pkg.github.com/carboclan/0x-mesh/0x-mesh:1.0
        restart: on-failure
        environment:
            ETHEREUM_RPC_URL: '${ETHEREUM_RPC_URL}'
            ETHEREUM_CHAIN_ID: '${CHAIN_ID}'
            USE_BOOTSTRAP_LIST: 'false'
            VERBOSITY: 3
            PRIVATE_KEY_PATH: ''
            WS_RPC_ADDR: '0.0.0.0:60557'
            HTTP_RPC_ADDR: '0.0.0.0:60556'
            BLOCK_POLLING_INTERVAL: '2s'
            ETHEREUM_RPC_MAX_REQUESTS_PER_24_HR_UTC: '150000'
        volumes:
          - ../.docker-volumes/0x_mesh:/usr/mesh/0x_mesh
        ports:
            - '60556:60556'
            - '60557:60557'
            - '60558:60558'
            - '60559:60559'
    api:
        depends_on:
            - postgres
            - mesh
        image: 0xorg/0x-api:latest
        restart: on-failure
        environment:
            ETHEREUM_RPC_URL: '${ETHEREUM_RPC_URL}'
            CHAIN_ID: '${CHAIN_ID}'
            MESH_WEBSOCKET_URI: 'http://mesh:60557'
            MESH_HTTP_URI: 'http://mesh:60556'
            POSTGRES_URI: 'postgresql://api:api@postgres/api'
            WHITELIST_ALL_TOKENS: '*'
        ports:
            - '80:3000'