# This is a basic workflow to help you get started with Actions

name: Staging Create Sentry Release

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ staging ]

jobs:
  release:
   runs-on: ubuntu-18.04
   env:
     SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
     SENTRY_ORG: michael-yankelev
     SENTRY_PROJECT: honeylemon-dapp
     SENTRY_DEPLOY_ENVIRONMENT: staging-kovan-28d

   steps: 
    - uses: actions/checkout@v1.0.0

    - name: Create new Sentry release and deploy to Heroku
      run: |
        yarn build
        # Install Sentry CLI
        curl -sL https://sentry.io/get-cli/ | bash
        sentry-cli --auth-token $SENTRY_AUTH_TOKEN
        # Create new Sentry release
        export SENTRY_RELEASE=$(sentry-cli releases propose-version)
        sentry-cli releases new -p $SENTRY_PROJECT $SENTRY_RELEASE
        sentry-cli releases set-commits --auto $SENTRY_RELEASE
        sentry-cli releases finalize $SENTRY_RELEASE
        
        # Create new deploy for this Sentry release
        sentry-cli releases deploys $SENTRY_RELEASE new -e $SENTRY_DEPLOY_ENVIRONMENT
